// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { existsSync } from "node:fs";
import { defineConfig } from "prisma/config";

const rawSchema = process.env.PRISMA_SCHEMA_PATH?.trim() || "prisma/schema.prisma";
const schemaCandidate =
  rawSchema.startsWith("prisma/") || rawSchema.startsWith("/")
    ? rawSchema
    : `prisma/${rawSchema}`;
const schema = existsSync(rawSchema)
  ? rawSchema
  : existsSync(schemaCandidate)
    ? schemaCandidate
    : rawSchema;
const normalizedSchema = schema.replace(/\\/g, "/");
const isPostgresSchema = normalizedSchema.endsWith("schema.postgres.prisma");
const migrationsPath =
  isPostgresSchema
    ? "prisma/migrations-postgres"
    : "prisma/migrations";

export default defineConfig({
  schema,
  migrations: {
    path: migrationsPath,
  },
});
