// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const schema = process.env.PRISMA_SCHEMA_PATH?.trim() || "prisma/schema.prisma";
const migrationsPath =
  schema === "prisma/schema.postgres.prisma"
    ? "prisma/migrations-postgres"
    : "prisma/migrations";

export default defineConfig({
  schema,
  migrations: {
    path: migrationsPath,
  },
});
